---
title: "git_00"
author: "Abel Jacobo perez"
date: "09,09,2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  

“Beware the Jabberwock, my son!
      
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
there's a bluebird in my heart that  
wants to get out  
but I'm too tough for him,  
I say, stay in there, I'm not going  
to let anybody see  
you.  
there's a bluebird in my heart that  
wants to get out  
but I pour whiskey on him and inhale  
cigarette smoke  
and the whores and the bartenders  
and the grocery clerks  
never know that  
he's  
in there.  

there's a bluebird in my heart that  
wants to get out  
but I'm too tough for him,  
I say,  
stay down, do you want to mess  
me up?  
you want to screw up the  
works?  
you want to blow my book sales in  
Europe?  
there's a bluebird in my heart that  
wants to get out  
but I'm too clever, I only let him out  
at night sometimes  
when everybody's asleep.  
I say, I know that you're there,  
so don't be  
sad.  
then I put him back,  
but he's singing a little  
in there, I haven't quite let him  
die  
and we sleep together like  
that  
with our  
secret pact  
and it's nice enough to  
make a man  
weep, but I don't  
weep, do  
you?  